```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE,
                      message=FALSE)
```

```{r load-packages}
library(tidyverse)
library(readr)
library(cowplot)
library(maps)
library(ggcorrplot)
library(ggplot2)
library(tidyr)

# Note: modified from Maria's old code. Didn't spend time to comment or make it pretty!

```



```{r data}

library(pROC)
data(aSAH)
rocobj <- roc(aSAH$outcome, aSAH$s100b)
rocobj2 <- roc(aSAH$outcome, aSAH$wfns)

library(ggplot2)
g <- ggroc(rocobj)
g
# with additional aesthetics:
ggroc(rocobj, alpha = 0.5, colour = "red", linetype = 2, size = 2)

# Multiple curves:
p1 <- ggroc(list(s100b=rocobj, wfns=rocobj2, ndka=roc(aSAH$outcome, aSAH$ndka)))+
  labs(title = " ", x = " ", y = " ") + 
  theme(legend.position = "none") +
  geom_line(size = 1.1) + 
  theme(
                plot.title = element_blank(),
                axis.title.x = element_blank(),
                axis.title.y = element_blank(),
                axis.ticks.x = element_blank(),
                axis.ticks.y = element_blank(),
                axis.text.x = element_blank(),
                axis.text.y = element_blank())

bikeshare <- read_csv("https://raw.githubusercontent.com/matackett/data/master/capital-bikeshare.csv")                          
bikeshare <- bikeshare %>%
  mutate(season = case_when(
    season==1 ~ "Winter",
    season==2 ~ "Spring",
    season==3 ~ "Summer",
    season==4 ~ "Fall"
  )) %>% 
  select(season,atemp,cnt)
alpha.level = 0.5 
bike2 <- bikeshare[bikeshare$season == "Winter",]
m1 <- lm(cnt~atemp, data = bike2)
ci <- predict(m1, newdata = data.frame(bike2), interval = "prediction")
p2 <- ggplot(data=cbind(bike2, ci),aes(x=atemp,y=cnt,color="forestgreen")) +
  geom_point(alpha=alpha.level) +
  geom_smooth(method = lm, se = TRUE, color = "forestgreen") +
  geom_line(aes(y=lwr), color = "darkblue", linetype = "dashed")+
  geom_line(aes(y=upr), color = "darkblue", linetype = "dashed")+
  geom_smooth(method=lm, se=TRUE)+
  theme_void() +
  theme(legend.position="none")

p3 <- ggplot(data=bikeshare,aes(x=cnt,fill=season)) +
  geom_density(alpha=alpha.level) +
  theme_void() +
  theme(legend.position="none")


data(mtcars)
corr <- round(cor(mtcars), 1)
p4 <- ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = F, 
           lab_size = 3, 
           method="circle", 
           colors = c("palevioletred", "white", "royalblue3"), 
           ggtheme=theme_bw) + theme_void() + theme(legend.position="none")

p5 <- ggplot(data=bikeshare,aes(x=season,y=cnt,fill=season)) +
  geom_violin() + 
  geom_boxplot(alpha=alpha.level) +
  theme_void() +
  theme(legend.position="none")

set.seed(1)
x1 <- rnorm(20, 0, 1)
y2 <- rnorm(20, 0, 1)
a1 <- rnorm(50, 0, 0.8) - 3
b1 <- rnorm(50, 0, 1.2) + 2

X <- c(x1, a1)
Y <- c(y2, b1)
datx <- as.data.frame(cbind(X, Y))

erup <- ggplot(datx, aes(x=X, y=Y)) 
p6 <- erup + geom_point() + geom_density_2d() + theme_void()+ xlim(-5.5, 2) + ylim(-2.5, 5)



library(survminer)
library(ggfortify)
setwd("C:/Users/Yue/Projects/Guest lecture")

library(survival)

got <- read.csv("got.csv")

got$screen <- got$s1_screenTime + got$s2_screenTime + got$s3_screenTime + 
        got$s4_screenTime + got$s5_screenTime + got$s6_screenTime +
        got$s7_screenTime

got$stark = ifelse(got$house == "Stark", 1, 0)
got$baratheon = ifelse(got$house == "Baratheon", 1, 0)
got$targaryen = ifelse(got$house == "Targaryen", 1, 0)
got$lannister = ifelse(got$house == "Lannister", 1, 0)

fit2 <- survfit(Surv(duration_in_episodes, is_dead) ~ gender, 
                data = got[got$gender != "",])

p7 <- autoplot(fit2) + 
        theme_bw()+ 
        theme(legend.position = "none") +
        theme(
                plot.title = element_blank(),
                axis.title.x = element_blank(),
                axis.title.y = element_blank(),
                axis.text.x = element_blank(),
                axis.text.y = element_blank())+
        xlim(c(0, 66))
```


# Plot

```{r plots}

plot_grid(p7,p3,p4,p6,p2,p1,ncol=3)
```

```{r save-plot}
# modify file location
ggsave("site-bg.png", width = 6*2.5, height = 4*2.5)
```





  